/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'token'] as const
  $columns = PasswordResetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
}

export class RutaSchema extends BaseModel {
  static $columns = ['apoyoAuxiliar', 'auxiliar', 'calibrada', 'capacidadKg', 'combustible', 'destinoTipologia', 'dia', 'efectividad', 'fecha', 'festivos', 'horaExtra', 'mes', 'numeroClientes', 'numeroFacturas', 'observaciones', 'parqueadero', 'peajes', 'peso', 'planilla', 'reenvio', 'ruta', 'semana', 'tarifa', 'taxis', 'tipoVehiculo', 'turno', 'valorDevolucion', 'valorReenvio', 'valorRuta', 'volumen', 'zona'] as const
  $columns = RutaSchema.$columns
  @column()
  declare apoyoAuxiliar: string | null
  @column()
  declare auxiliar: string | null
  @column()
  declare calibrada: number | null
  @column()
  declare capacidadKg: number | null
  @column()
  declare combustible: number | null
  @column()
  declare destinoTipologia: string | null
  @column()
  declare dia: string | null
  @column()
  declare efectividad: string | null
  @column()
  declare fecha: string | null
  @column()
  declare festivos: string | null
  @column()
  declare horaExtra: string | null
  @column()
  declare mes: string | null
  @column()
  declare numeroClientes: number | null
  @column()
  declare numeroFacturas: number | null
  @column()
  declare observaciones: string | null
  @column()
  declare parqueadero: number | null
  @column()
  declare peajes: number | null
  @column()
  declare peso: number | null
  @column()
  declare planilla: string | null
  @column()
  declare reenvio: number | null
  @column()
  declare ruta: string | null
  @column()
  declare semana: string | null
  @column()
  declare tarifa: number | null
  @column()
  declare taxis: number | null
  @column()
  declare tipoVehiculo: string | null
  @column()
  declare turno: string | null
  @column()
  declare valorDevolucion: number | null
  @column()
  declare valorReenvio: number | null
  @column()
  declare valorRuta: number | null
  @column()
  declare volumen: number | null
  @column()
  declare zona: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VehiculoSchema extends BaseModel {
  static $columns = ['capacidadKilo', 'claseVehiculo', 'createdAt', 'estado', 'id', 'marca', 'modelo', 'placa', 'tipo', 'updatedAt'] as const
  $columns = VehiculoSchema.$columns
  @column()
  declare capacidadKilo: number | null
  @column()
  declare claseVehiculo: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estado: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare marca: string | null
  @column()
  declare modelo: number | null
  @column()
  declare placa: string
  @column()
  declare tipo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
