/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RutaSchema extends BaseModel {
  static $columns = ['auxiliar', 'conductor', 'createdAt', 'destino', 'dia', 'empresa', 'fecha', 'finRuta', 'id', 'inicioRuta', 'kmFinal', 'kmInicial', 'mes', 'numeroClientes', 'numeroFacturas', 'observaciones', 'peso', 'placa', 'tiempoEnRuta', 'tipoVehiculo', 'totalKilometros', 'updatedAt', 'volumen', 'zona'] as const
  $columns = RutaSchema.$columns
  @column()
  declare auxiliar: string | null
  @column()
  declare conductor: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare destino: string | null
  @column()
  declare dia: string | null
  @column()
  declare empresa: string | null
  @column.date()
  declare fecha: DateTime | null
  @column()
  declare finRuta: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inicioRuta: string | null
  @column()
  declare kmFinal: number | null
  @column()
  declare kmInicial: number | null
  @column()
  declare mes: string | null
  @column()
  declare numeroClientes: number | null
  @column()
  declare numeroFacturas: number | null
  @column()
  declare observaciones: string | null
  @column()
  declare peso: number | null
  @column()
  declare placa: string | null
  @column()
  declare tiempoEnRuta: string | null
  @column()
  declare tipoVehiculo: string | null
  @column()
  declare totalKilometros: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare volumen: number | null
  @column()
  declare zona: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
